### ISSUE TITLE
compiling and running

### ISSUE THREAD

**Issue by xepost** [merosss/VRepRosQuadSwarm#1]
Hi,
 I downloaded your  code and compiled under  Ros hydro, but I  couldn't  find the proper method to run launch file. Roslaunch is asking  for some input.Can you  help  me on that?

Bests,

**Comment by lightng03** [comment]
Hello merosss, 
I am having trouble running this.
I am not able to run the following command
 `roslaunch quadcopter_ctrl swarmNodeCount_3.launch input:=map_file.txt`

I get the following error. Could you help me with this please

> Pos_Vec matrix not found!
process[quadNodeCount_2-4]: started with pid [15123]
[1] My zHeight is: 5.750000
Pos_Vec matrix not found!
[quadNodeCount_0-2] process has died [pid 15115, exit code 1, cmd /home/ravi/project_ws/devel/lib/quadcopter_ctrl/quadNodeCount 0 map_file.txt 5.0 sim 0 1 __name:=quadNodeCount_0 __log:=/home/ravi/.ros/log/3f5670e8-d833-11e5-a35a-8056f22be0d1/quadNodeCount_0-2.log].
log file: /home/ravi/.ros/log/3f5670e8-d833-11e5-a35a-8056f22be0d1/quadNodeCount_0-2*.log
[quadNodeCount_1-3] process has died [pid 15117, exit code 1, cmd /home/ravi/project_ws/devel/lib/quadcopter_ctrl/quadNodeCount 1 map_file.txt 5.75 sim 0 1 __name:=quadNodeCount_1 __log:=/home/ravi/.ros/log/3f5670e8-d833-11e5-a35a-8056f22be0d1/quadNodeCount_1-3.log].
log file: /home/ravi/.ros/log/3f5670e8-d833-11e5-a35a-8056f22be0d1/quadNodeCount_1-3*.log
[2] My zHeight is: 6.500000
Pos_Vec matrix not found!
[quadNodeCount_2-4] process has died [pid 15123, exit code 1, cmd /home/ravi/project_ws/devel/lib/quadcopter_ctrl/quadNodeCount 2 map_file.txt 6.5 sim 0 1 __name:=quadNodeCount_2 __log:=/home/ravi/.ros/log/3f5670e8-d833-11e5-a35a-8056f22be0d1/quadNodeCount_2-4.log].
log file: /home/ravi/.ros/log/3f5670e8-d833-11e5-a35a-8056f22be0d1/quadNodeCount_2-4*.log

Thanks

**Comment by merosss** [comment]
I made a quick fix, try to updating the repository and tell me if everything is now ok because I cannot test right now.

**Comment by lightng03** [comment]
Thanks for the update !
Now the Pos_Vec matrix ierror is solved. 
but when the simulation runs V-rep shows an error.

> Lua runtime error: [string "SCRIPT FastSimulationMode"]:18: attempt to perform arithmetic on global 'dlgStyle' (a nil value)
stack traceback:
	[string "SCRIPT FastSimulationMode"]:18: in main chunk

 I have attached a screen shot of the same

![screenshot from 2016-02-21 14 24 13](https://cloud.githubusercontent.com/assets/6937345/13205888/34ff625c-d8a7-11e5-885d-badc1a05c35d.png)

**Comment by merosss** [comment]
If you know how to edit the V-Rep `.lua` files associated to the scene you should edit it and disable the *fast simulation mode*. Otherwise I'll look into it and fix the bug asap.
BTW, which version of V-Rep are you using?

**Comment by lightng03** [comment]
I am using V-rep Pro edu 3.2.3 rev 4 64 bit version and rosversion is Indigo.
I am sorry I not good with .lua files, I am beginner. I'll try to edit it

**Comment by lightng03** [comment]
In the 3Rob_freeEnvironm scene, I commented out the line 18 in the FastSimulationMode. 
After this I am not getting any error but, when the simulation starts the screen goes black and returns to normal once the simulation is stopped.

**Comment by merosss** [comment]
Just delete the whole FastSimulationMode object by selecting and pressing "Canc", I tried it on v-rep 3.2.1 EDU and it worked.

**Comment by lightng03** [comment]
Hi Francesco!

Thanks for the help its working now I just tested out the swarmNodeCount3. Its working perfectly. 
Great work with the project. Ill test different scenarios and get back to you if i find anything

Cheers

**Comment by merosss** [comment]
Good! :smile: Closing the issue then

**Comment by jmzpawlak** [comment]
Hello,
Like lightng03 I have some similar problems with your project. I did everything that you write above and I have errors like that:

`process[OSListener-1]: started with pid [13493]
process[quadNodeCount_0-2]: started with pid [13494]
[0] My zHeight is: 5.000000
min_visit: 1
unvisitedCount: 11
quadNodeCount: /home/justyna/catkin_ws/src/quadcopter_ctrl/src/NodeCounting.cpp:114: void NodeCounting::createEdgeMat(): Assertion `n == access_vec.size()' **failed**.`

so the swarm doesn't move. Could you help me with it?
